### PR TITLE
Fix vls initialize is slow

### LINKED ISSUE #2453: VLS initialize is slow
Ref: https://github.com/vuejs/vetur/pull/2301#issuecomment-724723344

### PR DESCRIPTION
**Pull request by yoyo930021**
Fixed #2453

### CODE REVIEW

File: server/src/services/dependencyService.ts [hunk 1]
```diff
@@ -14,30 +14,50 @@ import { performance } from 'perf_hooks';
 import { logger } from '../log';
 
 const readFileAsync = util.promisify(fs.readFile);
+const existsFileAsync = util.promisify(fs.existsSync);
```
Comment (rchl) [inline server/src/services/dependencyService.ts:17]: Doesn't make sense to promisify sync version IMO. You'd probably want to promisy `fs.exists` instead (or `fs.stat` rather since `fs.exists` is deprecated).

Comment (yoyo930021) [reply server/src/services/dependencyService.ts]: Wow, thanks a lot.
I overtyped `Sync`.

File: server/src/services/dependencyService.ts [hunk 2]
```diff
@@ -14,30 +14,50 @@ import { performance } from 'perf_hooks';
 import { logger } from '../log';
 
 const readFileAsync = util.promisify(fs.readFile);
+const existsFileAsync = util.promisify(fs.exists);
```
Comment (rchl) [inline server/src/services/dependencyService.ts:17]: Would still recommend using non-deprecated API.

**Comment by rchl** [comment]
I'm seeing multiple instances of `[INFO ] Loaded typescript@4.0.5 from /Users/...` during initialize.

It's not only loading typescript from root of the `node_modules` but also within the dependencies, if those include typescript.

I know that dependencies should generally not include typescript as in `dependencies` but I have a couple of packages linked. But in any case, linked or not, should this be optimized to only try to load from the root of `node_modules`?

**Comment by yoyo930021** [comment]
> I'm seeing multiple instances of `[INFO ] Loaded typescript@4.0.5 from /Users/...` during initialize.
> 
> It's not only loading typescript from the root of the `node_modules` but also within the dependencies if those include typescript.
> 
> I know that dependencies should generally not include typescript in `dependencies` but I have a couple of packages linked. But in any case, linked or not, should this be optimized to only try to load from the root of `node_modules`?

This code was prepared for monorepo.
People should be able to use different versions of TypeScript in their projects.
Although the TypeScript ecosystem doesn't seem to allow it.

**Comment by rchl** [comment]
With the monorepo setup, the intention is that each sub-project will have its own `package.json`, right? So my suggestion should still be OK.

**Comment by yoyo930021** [comment]
> With the monorepo setup, the intention is that each sub-project will have its own `package.json`, right? So my suggestion should still be OK.
> 
> And it's not only about typescript. Other dependencies like prettier will also be searched and discovered in some deep sub-dependencies.

Your suggestion is good.
But this logic was prepared for the other libraries that came before it.
https://github.com/vuejs/vetur/blob/f37b9846873d613d0818d09268663618681395cb/server/src/utils/prettier/requirePkg.ts#L17
The main thing is that I want to be as consistent as possible with the require behavior.

**Comment by rchl** [comment]
But `require` wouldn't find dependency `c` located at `node_modules/a/node_modules/c` unless it would be called from `node_modules/a/index.js`, for example. So I'm not sure how current behavior is equivalent to `require`.

Note that I might not be seeing the whole picture...

**Comment by yoyo930021** [comment]
> But `require` wouldn't find dependency `c` located at `node_modules/a/node_modules/c` unless it would be called from `node_modules/a/index.js`, for example. So I'm not sure how current behavior is equivalent to `require`.
> 
> Note that I might not be seeing the whole picture...

You're right.

**Comment by yoyo930021** [comment]
@rchl Thanks a lot.
Can you help me test your project?

**Comment by rchl** [comment]
Looks good with the latest changes. It didn't find any extraneous typescript dependencies (only the single, expected one) or other dependencies. And it was relatively fast (~2s` for `initialize` response).
