### PR TITLE
Use typescript info for interpolation completion

### LINKED ISSUE #1129: Template interpolation completion doesn't work with object's props
- [ X ] I have searched through existing issues
- [ X ] I have read through [docs](https://vuejs.github.io/vetur)
- [ X ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version:  0.16.2
- VS Code version: 1.31.1

## Problem
vetur

### PR DESCRIPTION
**Pull request by ktsn**
fix #1129 

To use `ts.LanguageService#getCompletionsAtPosition` to get completion list for interpolation expression. It also combines previous completion info so that the behavior should be backward compatible.

~~There is a known issue when an interpolation expression is invalid. Our source map cannot handle expression position, then provides wrong completion in that case. We need to think how we handle invalid expression in the future.~~
-> Fixed via #1448 

```vue
<template>
  <div>{{ obj. }}</div> <!-- Cannot provide `obj.value` completion -->
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  data() {
    return {
      obj: { value: '' }
    }
  }
})
</script>
```

### CODE REVIEW

**Comment by sabifa** [comment]
I would love to see that feature! Could we get a small update about it, please? 😄

**Comment by octref** [comment]
I got completion resolve as well:

image

**Comment by octref** [comment]
Still need to fix the empty completion case `{{ | }}` but this is much better now.

File: test/interpolation/fixture/completion/Parent.vue [hunk 1]
```diff
@@ -35,7 +35,7 @@ export default {
      * My count
      */
     count () {
-      return this.$store.state.count
+      return 42;
```
Comment (octref) [inline test/interpolation/fixture/completion/Parent.vue]: I had to change this because otherwise the typing would be wrong and cause the whole `this` to have any type...

File: test/lsp/fixture/client/hover/Basic.vue [hunk 2]
```diff
@@ -26,7 +26,7 @@ export default {
   },
   computed: {
     count () {
-      return this.$store.state.count
+      return 42;
```
Comment (octref) [inline test/lsp/fixture/client/hover/Basic.vue]: I had to change this because otherwise the typing would be wrong and cause the whole `this` to have any type...

File: test/interpolation/fixture/completion/Parent.vue (hunk 1 above)
Comment (ktsn) [reply test/interpolation/fixture/completion/Parent.vue]: It's probably because of the return type annotation problem... 😢 
https://vuejs.org/v2/guide/typescript.html#Annotating-Return-Types

Comment (octref) [reply test/interpolation/fixture/completion/Parent.vue]: JSDocs return type doesn't work either. Sad..
