### PR TITLE
Fix/2430 sync modifier prop type checking

### LINKED ISSUE #2430: v-bind with .sync modifier and Vue template interpolation/type checking gives TypeScript error
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Problem

If `vetur.experimental.templateInterpolationService: true`, and using a v-bind with .sync modifier, TypeScript reports: 

`Property 'item' is missing in type '{ "item.sync": string; }' but required in type '{ item: string;  }'`

## Reproducible Case

```
<template>
    <SomeComponent :item.sync="item" />
</template>
```

SomeComponent.vue:

```
<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  props: {
    item: String,
  }
});
</script>
```

I have a fix, and will make a PR shortly.

It is caused by v-bind and v-on modifiers being appended in the same manner (originally to prevent duplicates causing errors from v-on chained modifiers). v-bind modifiers should always be culled from the node name, because we cannot bind one Vue prop twice (duplicates for v-bind are an error), and so that we aren't trying to find a prop with name "item.sync" rather than "item".

### PR DESCRIPTION
**Pull request by andrewisaburden**
Fixes #2430

### CODE REVIEW

File: server/src/services/typescriptService/transformTemplate.ts [hunk 1]
```diff
@@ -251,7 +251,7 @@ export function getTemplateTransformFunctions(ts: T_TypeScript, childComponentNa
         // Attribute name is specified
         // e.g. v-bind:value="foo"
         const fullName =
-          dir.key.modifiers.length === 0
+          dir.key.modifiers.length === 0 || !isVOn(dir)
```
Comment (yoyo930021) [inline server/src/services/typescriptService/transformTemplate.ts:254]: I think `&& isVBind(dir)` more intuitive.

**Review by yoyo930021 — CHANGES_REQUESTED** [review]

File: server/src/services/typescriptService/transformTemplate.ts (hunk 1 above)
Comment (andrewisaburden) [reply server/src/services/typescriptService/transformTemplate.ts:254]: @yoyo930021 I agree, and initially that's what I did. However, for reasons that are not clear to me, using `isVBind` with the typeguard of `: node is AST.VDirective` results in line 256 throwing this TypeScript error: `Property 'key' does not exist on type 'never'.` for the section `...dir.key.modifiers.map`.

This doesn't make sense to me, because `dir` is already of type `AST.VDirective` in the function parameters. I couldn't figure out a solution, if you know one please let me know.

Comment (andrewisaburden) [reply server/src/services/typescriptService/transformTemplate.ts:254]: After reading a little more, typeguards that are type predicates *only* do one thing: confirm the type is guarded.

`isVBind` actually should be split into two methods, one for `isVDirective` and one for `isVBind`. `isVDirective` should be a type guard, e.g. `function isVDirective(node: AST.VAttribute | AST.VDirective): node is AST.VDirective {`
and `isVBind` should not be a type guard: `function isVBind(node: AST.VAttribute | AST.VDirective): boolean {`

**Review by yoyo930021 — APPROVED** [review]

**Comment by yoyo930021** [comment]
@ktsn If you have time, you can take a look.
I think I'll merge first. If you have any questions, let me know.
