### PR TITLE
Fix #2324

### LINKED ISSUE #2324: [VTI] VTI should return exit code 1 and display more useful errors on unknown errors
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Problem

If VTI hits an error not already accounted for with the existing exception handlers, it just prints `VTI operation failed` with no further information. It also exits with error code 0.

## Proposed solution
     console.log(`VTI operation failed with error: ${_err}`);
     process.exit(1);

## Potential Problem

I'm less sure about this one, but also if there are no files it exits with error code 0 (success). I think ESLint does the same, but arguably it should be treated as a failure so that if, say, a CI pipeline tried to run VTI on the wrong directory with no found Vue files it should return a failure so that the mistake can be picked up.

I'm happy to fix these if the solutions are OK.

### PR DESCRIPTION
**Pull request by yoyo930021**
Fixed #2324

### CODE REVIEW

File: vti/src/cli.ts [hunk 1]
```diff
@@ -165,6 +165,6 @@ async function getDiagnostics(workspaceUri: URI) {
     console.log('  vti diagnostics ---- Print all diagnostics');
     console.log('');
   }
-})().catch(_err => {
-  console.error('VTI operation failed');
+})().catch(err => {
+  console.error(`VTI operation failed with error: ${err}`);
```
Comment (andrewisaburden) [inline vti/src/cli.ts:169]: I think it should use `process.exit(1);` after this
```suggestion
  console.error(`VTI operation failed with error: ${err}`);
  process.exit(1);
```

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,5 +1,8 @@
 # Changelog
 
+### 0.2x.0 | 2020-xx-xx |
+- 🙌 Display VTL errors. Thanks to contribution from [@yoyo930021](https://github.com/yoyo930021). #2324 and #2330.
```
Comment (andrewisaburden) [inline CHANGELOG.md:4]:
```suggestion
- 🙌 Display VTI errors. Thanks to contribution from [@yoyo930021](https://github.com/yoyo930021). #2324 and #2330.
```

Comment (yoyo930021) [reply CHANGELOG.md]: Thanks

**Comment by yoyo930021** [comment]
@andrewisaburden Thanks.
I'm sorry about I don't see `I'm happy to fix these if the solutions are OK.` in issue.

**Comment by andrewisaburden** [comment]
@yoyo930021 no problem :) I hope to make some more contributions to the project as it is helpful. If it's OK with you I will implement the vetur.config.js suggestion you gave? Some time next week.

**Comment by yoyo930021** [comment]
> @yoyo930021 no problem :) I hope to make some more contributions to the project as it is helpful. If it's OK with you I will implement the vetur.config.js suggestion you gave? Some time next week.

I think we can talk over this in #2325 with @octref .

**Review by octref — APPROVED** [review]
LGTM, thanks 👍
