### PR TITLE
fix #344: support postcss

### LINKED ISSUE #344: Style IntelliSense not working when I use postcss.
## Info

- Platform: macOS
- Vetur version: 0.9.1
- VSCode version: 1.14.1

## Problem

When I use postcss
wx20170719-143604 2x

When I use css
wx20170719-144652 2x
**I want this!!!!!!!!**

### PR DESCRIPTION
**Pull request by HerringtonDarkholme**

### CODE REVIEW

File: server/src/modes/style/index.ts [hunk 1]
```diff
@@ -92,7 +97,7 @@ export function cssFormat(document: TextDocument, currRange: Range, formattingOp
     cssFormattingOptions = _.assign(defaultCssOptions, formattingOptions.css);
   }
 
-  const beautifiedCss: string = cssBeautify(value, cssFormattingOptions);
+  const beautifiedCss = cssBeautify(value, cssFormattingOptions);
```
Comment (octref) [inline server/src/modes/style/index.ts]: Why remove this?

Comment (HerringtonDarkholme) [inline server/src/modes/style/index.ts]: Note `cssBeautify` already has return type `string`.  There is no need to redeclare the type.

I can also remember in older code, cssBeautify is typed as any because it comes from JS, so declaring beautifiedCss' type is needed. But later we turned on `noImplicitAny`so redeclaration is not needed any more.

**Comment by octref** [comment]
Thanks a lot!
