### PR TITLE
Impl monorepo and vetur config file support

### LINKED ISSUE #424: Multi root support
[Issuehunt badges](https://issuehunt.io/r/vuejs/vetur/issues/424)

Explore support for VSCode's new Multi-root workspace feature.
Notably, `rootPath` now can be a list.

https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs

This is somewhat different from #385, depending on the way the user uses VSCode.
For the following app,
```
/app
  /client
  /server
  /doc
```

- One might open `/app` in one Window. Vetur support for `/client` is #385.
- One might open `/app/client`, `/app/server` as two top-level folders. That's this issue.
- One might open two Vue apps as two top-level folders. That's this issue.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $250.00)

- [mesqueeb mesqueeb](https://issuehunt.io/u/mesqueeb) ($10.00)
- [garyo garyo](https://issuehunt.io/u/garyo) ($10.00)
- [tobspr tobspr](https://issuehunt.io/u/tobspr) ($100.00)
- $130.00 have been anonymously funded.

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/vuejs/vetur/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### LINKED ISSUE #815: Pick up tsconfig from non-top-level folder
[Issuehunt badges](https://issuehunt.io/r/vuejs/vetur/issues/815)

- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

Version 1.24.0
Commit 6a6e02cef0f2122ee1469765b704faf5d0e0d859
Date 2018-06-06T17:35:40.560Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
OS: Version: Windows 10.0.17134 Build 17134
Vetur version: 0.12.5

## Problem

**Error:**
{
	"resource": "/d:/Users/Eyal/Projects/Clients/DigitalTV/Web/experiment/dashboard/src/views/Home.vue",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "undefined",
	"severity": 8,
	"message": "Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.",
	"startLineNumber": 17,
	"startColumn": 22,
	"endLineNumber": 17,
	"endColumn": 26
}

**Image:**
image

**tsconfig.js file**
```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "node",
      "mocha",
      "chai"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "es2015",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

## Reproducible Case

1. mkdir experiment && cd $_
2. npm init
3. npm install -D `@vue/cli`
4.  ./node_modules/.bin/vue create dashboard
5. I've used the following options:

    * Check the features needed for your project: Babel, TS, PWA, Router, Vuex, CSS Pre-processors, Linter, Unit, E2E
    * Use class-style component syntax? Yes
    * Use Babel alongside TypeScript for auto-detected polyfills? Yes
    * Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): SCSS/SASS
    * Pick a linter / formatter config: TSLint
    * Pick additional lint features: Lint on save
    * Pick a unit testing solution: Mocha
    * Pick a E2E testing solution: Cypress
    * Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files
    * Save this as a preset for future projects? No

6. code .
7. Then navigate to dashboard/src/views/Home.vue

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $279.00)

- [eyalsk eyalsk](https://issuehunt.io/u/eyalsk) ($50.00)
- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($200.00)
- [ryanjaeb ryanjaeb](https://issuehunt.io/u/ryanjaeb) ($5.00)
- [egoist egoist](https://issuehunt.io/u/egoist) ($5.00)
- [morkro morkro](https://issuehunt.io/u/morkro) ($5.00)
- $14.00 have been anonymously funded.
### Submitted pull Requests
- [#1734 Subfolders and tsconfig support](https://issuehunt.io/r/vuejs/vetur/pull/1734)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/vuejs/vetur/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by yoyo930021**
Impl #2377 
Impl #2378 

Fixed #815
Fixed #424 

- [x] global components
- [x] watch ts and vetur config changed
- [x] watch package.json change
- [x] refactor
- [x] vti
- [x] multi-workspace
- [x] test
- [x] friendly warning
- [x] doctor command
- [ ] study node_module update
- [x] doc
- [x] changelog
- [x] shim-types docs

### CODE REVIEW

File: server/src/services/dependencyService.ts [hunk 1]
```diff
@@ -221,6 +217,17 @@ export const createDependencyService = () => {
   }
 
   const get = <L extends keyof RuntimeLibrary>(lib: L, filePath?: string): Dependency<RuntimeLibrary[L]> => {
+    // We find it when yarn pnp. https://yarnpkg.com/features/pnp
+    if (process.versions.pnp) {
+      const pkgPath = require.resolve(lib, { paths: [filePath ?? workspacePath] });
```
Comment (merceyz) [inline server/src/services/dependencyService.ts:222]: This will throw if the project doesn't depend on it and wont use the bundled version, also it shouldn't really branch like this, Vetur should always use `require.resolve` to locate dependencies instead of a custom version of the `node_modules` algorithm

File: server/src/services/dependencyService.ts [hunk 2]
```diff
@@ -91,124 +88,123 @@ export interface RuntimeLibrary {
...
+          bundled: true,
+          module: bundleModule as BM
+        }
+      ];
+    }
+  };
 
-    useWorkspaceDeps = useWorkspaceDependencies;
-    rootPath = workspacePath;
+  if (!process.versions.pnp) {
```
Comment (merceyz) [inline server/src/services/dependencyService.ts:207]: Typescript should still be loaded using the `tsdk` setting when using PnP

File: server/src/services/dependencyService.ts (hunk 1 above)
Comment (yoyo930021) [reply server/src/services/dependencyService.ts:222]: Hmm, I will fix it.

File: server/src/services/dependencyService.ts (hunk 2 above)
Comment (yoyo930021) [reply server/src/services/dependencyService.ts:207]: Thanks, I open a new issue about this problem.
https://github.com/vuejs/vetur/issues/2529
