### PR TITLE
Fix #1678 #2173 #2179

### LINKED ISSUE #1678: No CSS completions in `style` attribute inside `<template>` region
## Info
- Platform: macOS
- Vetur version:
- VS Code version:

## Problem

"files.associations": {
        "*.vue": "vue"
  }
then:
image

style snippet not work

"files.associations": {
        "*.vue": "html"
  }
then:
image

Vetur does not work

I hope to have code hints for inline styles, and also use Vetur.
Can this be achieved?

image
image

### PR DESCRIPTION
**Pull request by cereschen**
Now emmet works normally after interpolation:

image

Inline style emmet auto-complete support:

image

Custom event support:

image
image

### CODE REVIEW

File: server/src/modes/template/services/htmlCompletion.ts [hunk 1]
```diff
@@ -285,11 +285,15 @@ export function doComplete(
         break;
       case TokenType.AttributeValue:
         if (scanner.getTokenOffset() <= offset && offset <= scanner.getTokenEnd()) {
-          return collectAttributeValueSuggestions(
-            currentAttributeName,
-            scanner.getTokenOffset(),
-            scanner.getTokenEnd()
-          );
+          if (currentAttributeName === 'style') {
+            return emmet.doComplete(document, position, 'css', emmetConfig);
```
Comment (octref) [inline server/src/modes/template/services/htmlCompletion.ts:289]: During my test this would return `undefined` for such cases `<div style="|"></div>`. Need to handle that.
I think the result should be a combination of emmet/collectAttributeValueSuggestions.

**Comment by octref** [comment]
I found for `poa`, you need to manually trigger completion. This isn't ideal, but I haven't figured why that's happening. Other changes are good. Thank you 💯 🙏

**Comment by octref** [comment]
However I wouldn't say that's the correct way of setting up Component Data...Let me write the format down first.

**Comment by cereschen** [comment]
> However I wouldn't say that's the correct way of setting up Component Data...Let me write the format down first.

It's okay. I made my own decision 😅

**Comment by octref** [comment]
I added some integration test. Please familiarize yourself with how to add them for future PRs:

https://github.com/vuejs/vetur/wiki/Pull-Request-Guidance#integration-test
